### ISSUE TITLE
Miss All Sunday Infobox

### ISSUE THREAD

**Issue by simonhaga** [One-Pace/One-Pace#10]
http://mangaseeonline.us/read-online/One-Piece-chapter-114-page-8.html

**Comment by datenshi888** [comment]
https://www.dropbox.com/s/wn8gwlero5dsd46/Infobox-missAllSunday.png

**Comment by datenshi888** [comment]
Fixed infobox https://www.dropbox.com/s/edt9uboyeoblqbe/Infobox-missAllSunday_v2.png

**Comment by simonhaga** [comment]
missing transparency

**Comment by simonhaga** [comment]
Text slightly off-centered
