### ISSUE TITLE
Dressrosa 47

### ISSUE THREAD

**Issue by simonhaga** [One-Pace/One-Pace#9]
## How to QC
* One comment per user. Additional comments by the same user will be ignored. To edit an existing comment, press the pen icon in the top right corner of your comment.
* A comment may contain timestamps in a format like so:
  * 01:23 - Music seem slightly off.
  * 03:45 - This cut seems jarring.
  * 05:45 - The wind noise could be smoothed out a bit.
* They may also contain any additional information that may be of use to the editor.
* Comments may only be submitted while an issue is opened. Issues will in most cases be closed after a couple of days in order to keep the QC process short.
* Download links can be found over at [Discord](https://discordapp.com/channels/229653982530764800/347153755881472000).

**Comment by simonhaga** [comment]
Download here: https://www.dropbox.com/sh/weagxw60wdhf55i/AAComRiahIT1r-tVpCxme13Za

**Comment by slowcookedham** [comment]
- pacing, no problem

- cuts, no problem

- audio, no problem
